services:
  frontend:
    container_name: frontend-df-digital
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
  backend:
    container_name: backend-df-digital
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
    command: npm run dev
    depends_on:
      - db
  db:
    container_name: db-df-digital
    image: mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    ports:
      - "3306:3306"
    environment:
        LANG: C.UTF-8
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: dfDigital
        MYSQL_USER: user
        MYSQL_PASSWORD: user
    volumes:
        - ./backend/sql:/docker-entrypoint-initdb.d